FROM golang:1.21.4

ARG ATLAS_URI
ARG REDIS_HOST

ENV APP_HOME /go/src/job
ENV ATLAS_URI ${ATLAS_URI}
ENV REDIS_HOST ${REDIS_HOST}
ENV GIN_MODE=release

WORKDIR "$APP_HOME"

COPY ./job/go.mod .
COPY ./job/go.sum .

RUN go mod download

COPY ./job .
RUN go build -tags=jsoniter -o job 

CMD ["./job"]
