version: "2.4"
x-disable-external-refs: true

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "8888:8888"
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "9999:9999"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - ATLAS_URI=mongodb://host.docker.internal:9999
        - REDIS_HOST=host.docker.internal:8888
    ports:
      - "3000:3000"
  job:
    build:
      context: .
      dockerfile: Dockerfile.job
      args:
        - ATLAS_URI=mongodb://host.docker.internal:9999
        - REDIS_HOST=host.docker.internal:8888
