FROM golang:1.21.4

ARG ATLAS_URI
ARG REDIS_HOST

ENV APP_HOME /go/src/backend
ENV ATLAS_URI ${ATLAS_URI}
ENV REDIS_HOST ${REDIS_HOST}
ENV GIN_MODE=release

WORKDIR "$APP_HOME"

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build -tags=jsoniter -o backend 

EXPOSE 3000

CMD ["./backend"]
